export function architecture({ projectName, description, techStack, date }) {
  return `# ${projectName} — Architecture Overview

> **Last updated:** ${date} | Run \`devnexus index\` to generate code graph + GRAPH_REPORT.md

## What This Is

${description}

## Tech Stack

${techStack}

## How the Repos Connect

<!-- Describe how your repos talk to each other. Examples: -->
<!-- - Frontend calls backend API at /api/* -->
<!-- - Backend reads/writes to the database -->
<!-- - Shared types between repos -->

(Fill this in as you build.)

## Key Data Structures

<!-- List the most important models/schemas/types in your project. -->
<!-- These are the ones where a change ripples through multiple files. -->

(Fill this in as you build.)

## Key Communities

<!-- After running devnexus index, communities are auto-injected below. -->
<!-- See NODE_INDEX.md and GRAPH_REPORT.md for full details. -->

(Run \`devnexus index\` to populate.)

## Known Gaps

<!-- Things that are stored but not used, missing features, tech debt. -->

(Fill this in as you discover them.)
`;
}

export function moc({ projectName, vaultName, repos, date }) {
  const repoList = repos.map(r => `| [[${r}]] | Active | |`).join('\n');
  return `# Map of Content — ${projectName}

> Entry point for all agents. Read this first every session.

## Active Repos

| Repo | Status | Notes |
|------|--------|-------|
${repoList || '| (add repos) | Active | |'}

## Vault Files

| File | Purpose |
|------|---------|
| [[ARCHITECTURE_OVERVIEW]] | How the system works, key communities |
| [[API_CONTRACTS]] | Endpoint shapes — final authority |
| [[DECISIONS]] | Project-level decisions (license, tooling, infra) |
| [[decisions/DECISION_INDEX]] | Symbol-linked decisions — auto-generated index |
| [[GRAPH_REPORT]] | Structural analysis: nodes, edges, communities, god nodes |
| [[SESSION_LOG]] | Two-line handoff notes per session |

## Session Start Sequence

1. Read this file (MOC.md)
2. Read DECISIONS.md + decisions/DECISION_INDEX.md — what's been tried and why
3. For current work: check SESSION_LOG.md for last handoff
4. For architecture questions: ARCHITECTURE_OVERVIEW.md → GRAPH_REPORT.md

## Last Updated

${date}
`;
}

export function graphReport({ projectName, date }) {
  return `# Graph Report

> Auto-generated by \`devnexus index\`. Run it to populate.
> ${date} · Not yet generated

Run \`devnexus index\` after \`devnexus analyze\` to generate structural analysis:
- God nodes ranked by betweenness centrality
- Bridge edges between communities
- Knowledge gaps (thin, oversized, low-cohesion communities)
- Graph diff from previous index run
`;
}

export function apiContracts({ date }) {
  return `# API Contracts

> **Last updated:** ${date}
> If code and docs disagree, update the code. This file is the final authority.

## Endpoints

<!-- Document your API endpoints here. Example: -->
<!--
### POST /api/users
Creates a new user.
Request: { "email": "string", "name": "string" }
Response: { "id": "string", "email": "string", "name": "string" }
Errors: 400 (validation), 409 (duplicate email)
-->

(Add endpoints as you build them.)
`;
}

export function decisions({ date, author }) {
  return `# Decisions Log — Project Level

> Append-only log for **project-level** decisions that don't reference specific code symbols.
> Examples: license choices, tooling picks, infra decisions, team process choices.
> For decisions about specific functions/classes/symbols, use \`decisions/\` instead.
> Format: ## YYYY-MM-DD — Title (by [name]) followed by two sentences.

---

## ${date} — Workspace setup (by ${author})

Set up AI-augmented workspace with Obsidian vault as shared brain, CLAUDE.md for session context, and .ai-rules per repo. Vault is the single source of truth — agents read it before writing code.
`;
}

export function decisionsReadme() {
  return `# Symbol-Linked Decisions

> Each file in this directory is an atomic decision that references specific code symbols.
> \`devnexus index\` reads these files and injects backlinks into node files so agents see relevant decisions before editing.

## When to create a file here

When a decision involves specific functions, classes, types, or modules — e.g., "rejected splitting DealState" or "chose polling over websockets in syncEngine".

For project-level decisions (license, tooling, infra), append to \`../DECISIONS.md\` instead.

## File format

\`\`\`markdown
# Short decision title

Date: YYYY-MM-DD
Author: [name]
Status: ACTIVE
Refs: [[SymbolName]], [[OtherSymbol]]
Depends: YYYY-MM-DD-prior-decision.md

---

What was considered and why it was rejected/chosen. Free-form.
\`\`\`

## Fields

- **Date:** When the decision was made
- **Author:** Who made it
- **Status:** ACTIVE / SUPERSEDED / STALE (STALE is auto-set by \`devnexus index\` when ref'd symbols no longer exist)
- **Refs:** Wikilinks to symbols in the code graph. These trigger backlink injection into node files.
- **Depends:** Filename of a prior decision this builds on, reverses, or supersedes. Creates a decision chain.

## Naming convention

\`YYYY-MM-DD-short-slug.md\` — e.g., \`2026-04-16-dealstate-split-rejected.md\`

## What happens on \`devnexus index\`

1. All files here are parsed
2. \`DECISION_INDEX.md\` is auto-generated (do not edit it)
3. For each \`Refs:\` symbol found in the graph, a \`## Decisions\` section is injected into that symbol's node file
4. If a ref'd symbol no longer exists in the graph, the decision is flagged as STALE
`;
}

export function practicesReadme() {
  return `# Code Practices

> Project/team conventions, surfaced to agents BEFORE they write code.
> The devnexus MCP serves these via \`practices({ area })\` — one file per area.

## How it works

Each \`<area>.md\` here is callable by name. An agent about to write frontend code calls
\`practices({ area: "frontend" })\` and gets your conventions before writing, not after review.

## Adding an area

Drop a markdown file named after the area: \`frontend.md\`, \`auth.md\`, \`java.md\`, \`api.md\`, etc.
Keep each one a focused list of do/don't rules — these are read on every relevant edit.

## Wiring agents to use them

The \`.ai-rules/\` "Vault Brain (devnexus MCP)" rule already tells agents to call
\`practices({ area })\` before writing in an area. Name your files to match the areas you work in.
`;
}

export function practiceStarter(area) {
  const titles = {
    frontend: 'Frontend',
    auth: 'Auth & Sessions',
    api: 'API Design',
  };
  return `# ${titles[area] || area} Practices

> Conventions agents must follow before writing ${area} code. Replace these starters.

## Do

- (Add a rule. Example: validate all inputs at the boundary.)

## Don't

- (Add an anti-pattern. Example: never trust client-supplied IDs without a server check.)
`;
}

export function sessionLog() {
  return `# Session Log

> Two-line handoff notes at the end of each session.
> Helps the next session pick up where the last one left off.
> Format: ## YYYY-MM-DD — Session summary (by [name])
> Line 1: What was done. Line 2: Where things left off / what's next.

(No sessions logged yet.)
`;
}
